build-ironbsd:
    cd ../../stand/uefi && just build

setup-uefi-boot: build-ironbsd
    mkdir -p root/EFI/BOOT
    cp ../../stand/uefi/target/x86_64-unknown-uefi/release/loader.efi ./root/EFI/BOOT/bootx64.efi

start: setup-uefi-boot
    qemu-system-x86_64 \
        -enable-kvm \
        -m 4G \
        -drive if=pflash,format=raw,file=OVMF_CODE.4m.fd \
        -drive format=raw,file=fat:rw:root \
        -net none \
        -nographic
